import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

export const ROOT = process.cwd();
export const RAW_DIR = path.join(ROOT, 'data', 'raw');
export const NORMALIZED_DIR = path.join(ROOT, 'data', 'normalized');
export const GENERATED_DIR = path.join(ROOT, 'src', 'data', 'generated');

export async function ensureDir(dir) {
  await mkdir(dir, { recursive: true });
}

export async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, 'utf8'));
}

export async function writeJson(filePath, value) {
  await ensureDir(path.dirname(filePath));
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

export function slugify(value) {
  return String(value)
    .normalize('NFKD')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/_+/g, '-')
    .toLowerCase();
}

export function toTsConst(name, value) {
  return `// Generated by scripts/generate-data.mjs. Do not edit manually.\n\nexport const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

export function toTsArray(name, typeName, value) {
  return `// Generated by scripts/generate-data.mjs. Do not edit manually.\n\nimport { ${typeName} } from '../../types';\n\nexport const ${name}: ${typeName}[] = ${JSON.stringify(value, null, 2)};\n`;
}

export function parseSkillTargets(value) {
  if (!value) return [];
  return value
    .split(/[,\s]+/)
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const [skillId, rawLevel] = part.split(':');
      const targetLevel = Number(rawLevel ?? 1);
      if (!skillId || !Number.isFinite(targetLevel) || targetLevel <= 0) {
        throw new Error(`Invalid skill target: ${part}`);
      }
      return { skillId, targetLevel };
    });
}
